name: Upload data

on:
  workflow_dispatch:
    inputs:
      value1:
        description: "PR number"
        required: false
        default: "0"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/
