on:
  page_build:



jobs:
  triage:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "Comment about changes we can't accept"
        run: |
          echo "Hello, world!"
