on:
  push:


jobs:
  triage:
    permissions: write-all
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Comment about changes we can't accept"
        run: |
          echo "Hello, world!"
