name: GitHub Actions Demo
run-name: "Message: [${{ github.event.commits[0].message }}]"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: show
        run: |
          echo '${{ toJSON(github.event) }}'
