name: PR Workflow

on:
  pull_request:
    branches:
      - releases/1
    types:
      - opened

jobs:
  run_if:
    if: startsWith(github.head_ref, 'test/1')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'test/1'"
